"""add pantry_match_history table

Revision ID: 12b0db9e64ae
Revises: 128c8dbaa896
Create Date: 2025-12-28 02:03:36.353332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12b0db9e64ae"
down_revision: str | None = "128c8dbaa896"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pantry_match_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("normalized_ingredient", sa.String(length=255), nullable=False),
        sa.Column("normalized_pantry_name", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pantry_match_history_id"), "pantry_match_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pantry_match_history_normalized_ingredient"),
        "pantry_match_history",
        ["normalized_ingredient"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pantry_match_history_user_id"), "pantry_match_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pantry_match_history_user_id"), table_name="pantry_match_history")
    op.drop_index(
        op.f("ix_pantry_match_history_normalized_ingredient"), table_name="pantry_match_history"
    )
    op.drop_index(op.f("ix_pantry_match_history_id"), table_name="pantry_match_history")
    op.drop_table("pantry_match_history")
    # ### end Alembic commands ###
