"""add_image_path_to_recipes

Revision ID: 1641c3cc0ad1
Revises: 77a1e10b4e02
Create Date: 2025-12-31 18:29:40.966559

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1641c3cc0ad1"
down_revision: str | None = "77a1e10b4e02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("image_path", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "image_path")
    # ### end Alembic commands ###
