"""rename accountability_partner_email to phone

Revision ID: 24a12a50937a
Revises: 97809157912f
Create Date: 2026-01-01 17:09:22.432818

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24a12a50937a"
down_revision: str | None = "97809157912f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notification_settings",
        sa.Column("accountability_partner_phone", sa.String(length=20), nullable=True),
    )
    op.drop_column("user_notification_settings", "accountability_partner_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notification_settings",
        sa.Column(
            "accountability_partner_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user_notification_settings", "accountability_partner_phone")
    # ### end Alembic commands ###
