"""add preferred_store to pantry_items

Revision ID: 3cfc4495f153
Revises: 5629dbc4b062
Create Date: 2025-12-28 15:44:08.363677

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cfc4495f153"
down_revision: str | None = "5629dbc4b062"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pantry_items", sa.Column("preferred_store", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pantry_items", "preferred_store")
    # ### end Alembic commands ###
