"""Add receipt_scans table

Revision ID: 5629dbc4b062
Revises: 9a575656375c
Create Date: 2025-12-28 09:53:28.969519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5629dbc4b062"
down_revision: str | None = "9a575656375c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipt_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("parsed_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("items_added", sa.Integer(), nullable=True),
        sa.Column("items_updated", sa.Integer(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipt_scans_id"), "receipt_scans", ["id"], unique=False)
    op.create_index(op.f("ix_receipt_scans_user_id"), "receipt_scans", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_scans_user_id"), table_name="receipt_scans")
    op.drop_index(op.f("ix_receipt_scans_id"), table_name="receipt_scans")
    op.drop_table("receipt_scans")
    # ### end Alembic commands ###
