"""add_voice_debug_info_column

Revision ID: 6bdab1b936db
Revises: bf47c0f97f64
Create Date: 2026-01-04 02:14:59.330884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bdab1b936db'
down_revision: Union[str, None] = 'bf47c0f97f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('voice_debug_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'voice_debug_info')
    # ### end Alembic commands ###
