"""Add nutrition fields to recipes

Revision ID: 845e34fbe44f
Revises: a1b2c3d4e5f6
Create Date: 2025-12-28 09:31:33.902784

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "845e34fbe44f"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("calories_per_serving", sa.Integer(), nullable=True))
    op.add_column("recipes", sa.Column("protein_grams", sa.Float(), nullable=True))
    op.add_column("recipes", sa.Column("carbs_grams", sa.Float(), nullable=True))
    op.add_column("recipes", sa.Column("fat_grams", sa.Float(), nullable=True))
    op.add_column(
        "recipes", sa.Column("nutrition_computed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "nutrition_computed_at")
    op.drop_column("recipes", "fat_grams")
    op.drop_column("recipes", "carbs_grams")
    op.drop_column("recipes", "protein_grams")
    op.drop_column("recipes", "calories_per_serving")
    # ### end Alembic commands ###
