"""add notification system tables

Revision ID: 97809157912f
Revises: a663a531e286
Create Date: 2026-01-01 06:23:49.853415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97809157912f"
down_revision: str | None = "a663a531e286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=False),
        sa.Column("p256dh_key", sa.String(length=200), nullable=False),
        sa.Column("auth_key", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "endpoint", name="uq_user_endpoint"),
    )
    op.create_index(op.f("ix_push_subscriptions_id"), "push_subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "user_notification_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("accountability_partner_phone", sa.String(length=20), nullable=True),
        sa.Column("escape_safe_word", sa.String(length=50), nullable=True),
        sa.Column("escalation_timing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("quiet_hours_timezone", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_notification_settings_id"), "user_notification_settings", ["id"], unique=False
    )
    op.create_table(
        "reminder_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("current_escalation_level", sa.Integer(), nullable=True),
        sa.Column("last_escalation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_escalation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "acknowledged", "completed", "escaped", name="reminderstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminder_states_id"), "reminder_states", ["id"], unique=False)
    op.create_index(
        op.f("ix_reminder_states_item_id"), "reminder_states", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_states_next_escalation_at"),
        "reminder_states",
        ["next_escalation_at"],
        unique=False,
    )
    op.create_table(
        "reminder_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reminder_state_id", sa.Integer(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("push", "sms", "call", "app", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column("raw_response", sa.Text(), nullable=False),
        sa.Column("llm_interpretation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reminder_state_id"],
            ["reminder_states.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminder_responses_id"), "reminder_responses", ["id"], unique=False)
    op.create_index(
        op.f("ix_reminder_responses_reminder_state_id"),
        "reminder_responses",
        ["reminder_state_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminder_responses_reminder_state_id"), table_name="reminder_responses")
    op.drop_index(op.f("ix_reminder_responses_id"), table_name="reminder_responses")
    op.drop_table("reminder_responses")
    op.drop_index(op.f("ix_reminder_states_next_escalation_at"), table_name="reminder_states")
    op.drop_index(op.f("ix_reminder_states_item_id"), table_name="reminder_states")
    op.drop_index(op.f("ix_reminder_states_id"), table_name="reminder_states")
    op.drop_table("reminder_states")
    op.drop_index(op.f("ix_user_notification_settings_id"), table_name="user_notification_settings")
    op.drop_table("user_notification_settings")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
