"""Add last_cooked_at to recipes

Revision ID: 9a575656375c
Revises: 845e34fbe44f
Create Date: 2025-12-28 09:41:44.582055

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a575656375c"
down_revision: str | None = "845e34fbe44f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("last_cooked_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "last_cooked_at")
    # ### end Alembic commands ###
