"""add label_color to recipes

Revision ID: b38c0ebf1f16
Revises: 12b0db9e64ae
Create Date: 2025-12-28 02:27:42.316130

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b38c0ebf1f16"
down_revision: str | None = "12b0db9e64ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("label_color", sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "label_color")
    # ### end Alembic commands ###
