"""add_voice_refinement_fields

Revision ID: bf47c0f97f64
Revises: 24a12a50937a
Create Date: 2026-01-04 00:54:23.144149

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf47c0f97f64"
down_revision: str | None = "24a12a50937a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("refinement_status", sa.String(length=20), nullable=True))
    op.add_column("items", sa.Column("raw_voice_text", sa.String(length=2000), nullable=True))
    op.create_index(
        op.f("ix_items_refinement_status"), "items", ["refinement_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_refinement_status"), table_name="items")
    op.drop_column("items", "raw_voice_text")
    op.drop_column("items", "refinement_status")
    # ### end Alembic commands ###
