"""Add recipe management tables

Revision ID: d001ec64829d
Revises: d1316c142a82
Create Date: 2025-12-27 20:43:11.655820

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d001ec64829d"
down_revision: str | None = "d1316c142a82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_store_defaults",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("store_preference", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "normalized_name", name="uq_user_ingredient_default"),
    )
    op.create_index(
        op.f("ix_ingredient_store_defaults_id"), "ingredient_store_defaults", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ingredient_store_defaults_normalized_name"),
        "ingredient_store_defaults",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingredient_store_defaults_user_id"),
        "ingredient_store_defaults",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "recipe_add_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_add_events_id"), "recipe_add_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_recipe_add_events_user_id"), "recipe_add_events", ["user_id"], unique=False
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("servings", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.create_index(op.f("ix_recipes_user_id"), "recipes", ["user_id"], unique=False)
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("store_preference", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_ingredients_id"), "recipe_ingredients", ["id"], unique=False)
    op.create_index(
        op.f("ix_recipe_ingredients_recipe_id"), "recipe_ingredients", ["recipe_id"], unique=False
    )
    op.create_table(
        "recipe_add_event_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("original_quantity", sa.String(length=100), nullable=True),
        sa.Column("original_recipe_sources", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("added_quantity", sa.String(length=100), nullable=True),
        sa.Column("added_recipe_sources", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["recipe_add_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_add_event_items_event_id"),
        "recipe_add_event_items",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipe_add_event_items_id"), "recipe_add_event_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recipe_add_event_items_item_id"),
        "recipe_add_event_items",
        ["item_id"],
        unique=False,
    )
    op.add_column(
        "items", sa.Column("recipe_sources", postgresql.JSON(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "recipe_sources")
    op.drop_index(op.f("ix_recipe_add_event_items_item_id"), table_name="recipe_add_event_items")
    op.drop_index(op.f("ix_recipe_add_event_items_id"), table_name="recipe_add_event_items")
    op.drop_index(op.f("ix_recipe_add_event_items_event_id"), table_name="recipe_add_event_items")
    op.drop_table("recipe_add_event_items")
    op.drop_index(op.f("ix_recipe_ingredients_recipe_id"), table_name="recipe_ingredients")
    op.drop_index(op.f("ix_recipe_ingredients_id"), table_name="recipe_ingredients")
    op.drop_table("recipe_ingredients")
    op.drop_index(op.f("ix_recipes_user_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_recipe_add_events_user_id"), table_name="recipe_add_events")
    op.drop_index(op.f("ix_recipe_add_events_id"), table_name="recipe_add_events")
    op.drop_table("recipe_add_events")
    op.drop_index(
        op.f("ix_ingredient_store_defaults_user_id"), table_name="ingredient_store_defaults"
    )
    op.drop_index(
        op.f("ix_ingredient_store_defaults_normalized_name"), table_name="ingredient_store_defaults"
    )
    op.drop_index(op.f("ix_ingredient_store_defaults_id"), table_name="ingredient_store_defaults")
    op.drop_table("ingredient_store_defaults")
    # ### end Alembic commands ###
