"""Add voice input and pending confirmation models

Revision ID: d1316c142a82
Revises: af087f049b12
Create Date: 2025-12-08 03:09:27.561366

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1316c142a82"
down_revision: str | None = "af087f049b12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_confirmations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("voice_input_id", sa.Integer(), nullable=False),
        sa.Column("proposed_changes", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pending_confirmations_id"), "pending_confirmations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pending_confirmations_status"), "pending_confirmations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pending_confirmations_user_id"), "pending_confirmations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_pending_confirmations_voice_input_id"),
        "pending_confirmations",
        ["voice_input_id"],
        unique=False,
    )
    op.create_table(
        "voice_inputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voice_inputs_id"), "voice_inputs", ["id"], unique=False)
    op.create_index(op.f("ix_voice_inputs_status"), "voice_inputs", ["status"], unique=False)
    op.create_index(op.f("ix_voice_inputs_user_id"), "voice_inputs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_inputs_user_id"), table_name="voice_inputs")
    op.drop_index(op.f("ix_voice_inputs_status"), table_name="voice_inputs")
    op.drop_index(op.f("ix_voice_inputs_id"), table_name="voice_inputs")
    op.drop_table("voice_inputs")
    op.drop_index(
        op.f("ix_pending_confirmations_voice_input_id"), table_name="pending_confirmations"
    )
    op.drop_index(op.f("ix_pending_confirmations_user_id"), table_name="pending_confirmations")
    op.drop_index(op.f("ix_pending_confirmations_status"), table_name="pending_confirmations")
    op.drop_index(op.f("ix_pending_confirmations_id"), table_name="pending_confirmations")
    op.drop_table("pending_confirmations")
    # ### end Alembic commands ###
